name: Calculate ImpHash

on:
  push:
    branches:
      - main  # Replace with the branch name where you want to trigger the workflow

jobs:
  calculate_imphash:
    runs-on: ubuntu-latest  # Replace with the desired runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6  # Replace with the desired Python version

      - name: Install pefile
        run: pip install pefile

      - name: Calculate ImpHash
        run: |
          python calculate_imphash.py

      - name: Configure Git
        run: |
          git config --global user.name "ahsan saeed"
          git config --global user.email "ahsansaeed878@gmail.com"
      
      - name: Commit changes
        run: |
          git add imphash.txt
          git commit -m "Update imphash.txt"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}