name: Calculate ImpHash

on:
  push:
    branches:
      - main  # Replace with the branch name where you want to trigger the workflow

jobs:
  calculate_imphash:
    runs-on: ubuntu-latest  # Replace with the desired runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6  # Replace with the desired Python version

      - name: Install pefile
        run: pip install pefile

      - name: Calculate ImpHash
        run: |
          python calculate_imphash.py
      - name: Upload imphash.txt
        uses: actions/upload-artifact@v2
        with:
          name: imphash-results
          path: imphash.txt